version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: master
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: always

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
